name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ['debian:11', 'debian:12', 'ubuntu:20.04', 'ubuntu:22.04', 'ubuntu:24.04']
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build squid
        run: bash build.sh

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: debian-package-${{ hashFiles('./pkgs/*.deb') }}
          path: ./pkgs/*.deb
  build-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv6l, armv7l, aarch64]
        include:
        - arch: armv6l
          cpu: arm1176
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_zero_w
        - arch: armv7l
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_zero2_w
        - arch: aarch64
          cpu: cortex-a53
          base_image: raspios_lite_arm64:latest
          cpu_info: cpuinfo/raspberrypi_zero2_w_arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: pguyot/arm-runner-action@v2
      with:
        base_image: ${{ matrix.base_image }}
        cpu: ${{ matrix.cpu }}
        cpu_info: ${{ matrix.cpu_info }}
        image_additional_mb: 1000
        optimize_image: no
        commands: |
            bash build.sh

    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: debian-package-${{ matrix.arch }}-${{ hashFiles('./pkgs/*.deb') }}
        path: ./pkgs/*.deb
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: 
      - build
      - build-arm
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./pkgs
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./pkgs/*.deb"
          tag: ${{ github.ref_name }}
