name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ['debian:11', 'debian:12', 'ubuntu:20.04', 'ubuntu:22.04', 'ubuntu:24.04']
        arch: ['amd64', 'arm/v7', 'arm64/v8']
    container:
      image: ${{ matrix.container }}
      options: --platform linux/${{ matrix.arch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build squid
        run: bash build.sh

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: debian-package-${{ matrix.container }}-${{ matrix.arch }}
          path: ./pkgs/*.deb
  
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: ./pkgs
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./pkgs/*.deb"
          tag: ${{ github.ref_name }}
